### ISSUE TITLE
Yarn 2 (berry) pnp support

### ISSUE THREAD

**Issue by raulmax319** [mikehardy/jetifier#69]
### System: 

- OS: Windows 11 Pro
- OS build 22000.51

### Binaries

- Node: 16.1.0
- Yarn: 2.4.2

### Steps to reproduce

```bash
$ npx react-native init reproject --template react-native-template-typescript
$ yarn set version berry
$ rm -rf node-modules
```
Add the following lines to your yarnrc.yml
```yml
yarnPath: '.yarn/releases/yarn-berry.cjs'
nodeLinker: 'pnp'
packageExtensions:
  'metro-config@*':
    dependencies:
      'metro-transform-worker': '*'
```
```bash
$ yarn install
$ npx jetify
```
### Behavior

On run, yarn pnp mode gives the following error:
```
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'node_modules'
    at Object.readdirSync (node:fs:1381:3)
    at NodeFS.readdirSync (F:\pkgs\RNSlider\.pnp.js:12887:26)
    at makeCallSync.subPath.subPath (F:\pkgs\RNSlider\.pnp.js:15683:26)  
    at ZipOpenFS.makeCallSync (F:\pkgs\RNSlider\.pnp.js:15783:26)        
    at ZipOpenFS.readdirSync (F:\pkgs\RNSlider\.pnp.js:15682:17)
    at VirtualFS.readdirSync (F:\pkgs\RNSlider\.pnp.js:13178:24)
    at PosixFS.readdirSync (F:\pkgs\RNSlider\.pnp.js:13178:24)
    at readDir (F:\pkgs\RNSlider\.yarn\unplugged\jetifier-npm-2.0.0-c3dff52ce1\node_modules\jetifier\src\utils.js:14:17)
    at Object.<anonymous> (F:\pkgs\RNSlider\.yarn\unplugged\jetifier-npm-2.0.0-c3dff52ce1\node_modules\jetifier\index.js:12:15)
    at Module._compile (node:internal/modules/cjs/loader:1109:14) {      
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'node_modules'
}
```

**Comment by mikehardy** [comment]
Hi there! This module is deprecated, no further development will happen here.
It's in the process of being phased out of react-native CLI, and I encourage you to 

1- use the --no-jetifier flag on the react-native CLI in order to disable it
2- make upstream patches on any modules (there should not be any?) that still have not converted to AndroidX in the 2 years since it has been out

In my projects I can run successfully without needing jetifier now so this is not an unreasonable stance, it should be possible, and any effort spent should be spent on fixing whatever modules haven't moved yet, vs any work here

Cheers

**Comment by raulmax319** [comment]
I see, thanks for the clarification 😊
